GET {{host}}/api/order/list
Accept: application/json

###
POST {{host}}/api/order/create
Content-Type: application/json

{
    "items": [
        {
            "menu": "choco_latte",
            "arguments": {
                "count": 1,
                "shot": 1,
                "temperature": "HOT"
            }
        }
    ]
}

