GET http://{{host}}/api/reservation/2401280930
Accept: application/json

###
POST http://{{host}}/api/reservation/2401280930/cancel
Content-Type: application/json

###
GET http://{{host}}/api/reservation/list
Accept: application/json

###
POST http://{{host}}/api/reservation/take
Content-Type: application/json

{
    "password": "hello",
    "name": "총포과",
    "order": {
        "items": [
            {
                "menu": "latte",
                "arguments": {
                    "count": 1,
                    "temperature": "HOT",
                    "shot": 1
                }
            }
        ]
    },
    "time": "2024-01-26 10:30:00",
    "for_meeting": true
}